// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package cmdpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountReq struct {
	Op                   int32    `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountReq) Reset()         { *m = AccountReq{} }
func (m *AccountReq) String() string { return proto.CompactTextString(m) }
func (*AccountReq) ProtoMessage()    {}
func (*AccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *AccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountReq.Unmarshal(m, b)
}
func (m *AccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountReq.Marshal(b, m, deterministic)
}
func (m *AccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountReq.Merge(m, src)
}
func (m *AccountReq) XXX_Size() int {
	return xxx_messageInfo_AccountReq.Size(m)
}
func (m *AccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountReq proto.InternalMessageInfo

func (m *AccountReq) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *AccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountResp struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CiperTxt             string   `protobuf:"bytes,3,opt,name=ciperTxt,proto3" json:"ciperTxt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResp) Reset()         { *m = AccountResp{} }
func (m *AccountResp) String() string { return proto.CompactTextString(m) }
func (*AccountResp) ProtoMessage()    {}
func (*AccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResp.Unmarshal(m, b)
}
func (m *AccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResp.Marshal(b, m, deterministic)
}
func (m *AccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResp.Merge(m, src)
}
func (m *AccountResp) XXX_Size() int {
	return xxx_messageInfo_AccountResp.Size(m)
}
func (m *AccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResp proto.InternalMessageInfo

func (m *AccountResp) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

func (m *AccountResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountResp) GetCiperTxt() string {
	if m != nil {
		return m.CiperTxt
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountReq)(nil), "cmdpb.AccountReq")
	proto.RegisterType((*AccountResp)(nil), "cmdpb.AccountResp")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0xce, 0x4d, 0x29, 0x48,
	0x52, 0xb2, 0xe0, 0xe2, 0x72, 0x84, 0x88, 0x07, 0xa5, 0x16, 0x0a, 0xf1, 0x71, 0x31, 0xe5, 0x17,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0xe5, 0x17, 0x08, 0x49, 0x71, 0x71, 0x14, 0x24,
	0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x4a,
	0xe1, 0x5c, 0xdc, 0x70, 0x9d, 0xc5, 0x05, 0x42, 0x42, 0x5c, 0x2c, 0x45, 0xa9, 0xc5, 0x10, 0xcd,
	0x9c, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0x31, 0x54,
	0x37, 0x8c, 0x0b, 0x32, 0x38, 0x39, 0xb3, 0x20, 0xb5, 0x28, 0xa4, 0xa2, 0x44, 0x82, 0x19, 0x62,
	0x30, 0x8c, 0x6f, 0xe4, 0xca, 0xc5, 0x05, 0x75, 0x6a, 0x70, 0x51, 0x99, 0x90, 0x39, 0x17, 0x0f,
	0xd4, 0x1a, 0xe7, 0xdc, 0x14, 0x97, 0x7c, 0x21, 0x41, 0x3d, 0xb0, 0xc3, 0xf5, 0x10, 0xae, 0x96,
	0x12, 0x42, 0x17, 0x2a, 0x2e, 0x50, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd3, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0xdc, 0x6c, 0x33, 0xf8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountSrvClient is the client API for AccountSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountSrvClient interface {
	AccountCmdDo(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*AccountResp, error)
}

type accountSrvClient struct {
	cc *grpc.ClientConn
}

func NewAccountSrvClient(cc *grpc.ClientConn) AccountSrvClient {
	return &accountSrvClient{cc}
}

func (c *accountSrvClient) AccountCmdDo(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/cmdpb.accountSrv/AccountCmdDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountSrvServer is the server API for AccountSrv service.
type AccountSrvServer interface {
	AccountCmdDo(context.Context, *AccountReq) (*AccountResp, error)
}

func RegisterAccountSrvServer(s *grpc.Server, srv AccountSrvServer) {
	s.RegisterService(&_AccountSrv_serviceDesc, srv)
}

func _AccountSrv_AccountCmdDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountSrvServer).AccountCmdDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdpb.accountSrv/AccountCmdDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountSrvServer).AccountCmdDo(ctx, req.(*AccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdpb.accountSrv",
	HandlerType: (*AccountSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountCmdDo",
			Handler:    _AccountSrv_AccountCmdDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
